site_name: ros2-jetson
theme:
    name: "material"
    favicon: images/favicon.ico
    palette:
        primary: green
        secondary: light green
nav:
    - Home: 'index.md'
    - ROS2_packages : 'ros2-packages.md'
    - Libraries : 'libraries.md'
    - Containers : 'ros2-jetson-dockers.md'
    - Blogs : 'blogs.md'

